# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9abc3db8529d1be0b19e4f131e97730f074925f7ba652bfb49dc522787eaec2e6cf4a7a46dd4df5527a310df457e3e1417bdb6a55b8e680eca40e780930eefa

test:
  secret_key_base: b55ad4843704ced8841bba5877a93c7e1269f2690850e06270e464e810b6a13fa91bd9f6acacf1bd585669628f225f64f61470071cda983ddebe1a91155f6c5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
